name: xpath_parse
description: xpath package for dart, uses a path expression to select node or a list of nodes from an XML document.
version: 2.0.0
homepage: "https://github.com/codingfd/xpath"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html: ^0.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3

